### ISSUE TITLE
Customizing OpenSeadragon Gestures in IIIF VIewer Block

### ISSUE THREAD

**Issue by mathewjordan** [inseri-swiss/inseri-swiss#101]
Awesome plugin. Just a quick note!

Relating to your implementation of [Clover IIIF](https://github.com/inseri-swiss/inseri-core-wp/blob/3b3a4ffb2e5b73554eb69641654c1669342e653f/src/blocks/iiifViewer/view.tsx#L56-L67),  you can customize the `openSeadragon` options to avoid the user's cursor being trapped in the OpenSeadragon canvas while navigating the page. This might lead to better user experience in WordPress style articles and pages. 

See https://codesandbox.io/s/clover-osd-gestures-yxnlt7?file=/src/App.jsx:278-382

```jsx
<CloverViewer
  iiifContent={iiifContent}
  options={{
    showTitle: true,
    openSeadragon: {
      gestureSettingsMouse: {
        scrollToZoom: false
      }
    }
 }}
/>
```

Additionally, mobile experience is a bit harder to work around due to limitations in OpenSeadragon `touch` gestures. I advise handling this by use of [`placeholderCanvas`](https://iiif.io/api/cookbook/recipe/0013-placeholderCanvas/) in Manifests which Clover supports. See a Manifest with [`placeholderCanvas` on Image canvases](https://samvera-labs.github.io/clover-iiif/docs/viewer/demo?iiif-content=https://api.dc.library.northwestern.edu/api/v2/works/ce94e4f6-d038-4d90-93e1-d6b8900ca038?as=iiif).

Best 💯

**Comment by bigaru** [comment]
Thanks for the precious inputs.
I see that mobile UX is tricky.  Since `placeholderCanvas` is provided by the manifest, there is no need to configure Clover-IIIF to improve mobile UX, right?

**Comment by mathewjordan** [comment]
> Thanks for the precious inputs. I see that mobile UX is tricky. Since `placeholderCanvas` is provided by the manifest, there is no need to configure Clover-IIIF to improve mobile UX, right?

I've thought about this @bigaru. Most Manifests do not carry `placeholderCanvas`, but I could envision an options prop `forcePlaceholderCanvas`, in the viewer that when set to `true` (perhaps default `false`) attempted to build a `placeholderCanvas` on the fly using the current `activeCanvas`. This constructed placeholder would not exist on the actual Manifest being shown, but you could inform the viewer (Clover) to render it as if it were.

**Comment by mathewjordan** [comment]
> Thanks for the precious inputs. I see that mobile UX is tricky. Since `placeholderCanvas` is provided by the manifest, there is no need to configure Clover-IIIF to improve mobile UX, right?

Clover will automatically detect a `placeholderCanvas` if it exists for the activeCanvas and attempt to render it. This renders in place of OpenSeadragon and can be turned on/off by the user.

**Comment by bigaru** [comment]
Thanks again for the elaborated response.
I will close this issue by adding the flag `scrollToZoom`.  Regarding `placeholderCanvas`, we will take action based on users feedback or the newer version of CloverIIIF.
