### ISSUE TITLE
A new showcase

### ISSUE THREAD

**Issue by bigaru** [inseri-swiss/inseri-swiss#128]
* https://support.strava.com/hc/en-us/articles/216918437-Exporting-your-Data-and-Bulk-Export
* https://towardsdatascience.com/visualize-your-strava-data-on-an-interactive-map-with-python-92c1ce69e91d

**Comment by aplamada** [comment]
The blog uses [`folium`](https://github.com/python-visualization/folium) to display the map which relies on [`Leaflet.js`](https://leafletjs.com/) that I do not expect to work.

**Comment by aplamada** [comment]
https://inseri.swiss/2024/05/global-student-visa-cost/ published.
