### ISSUE TITLE
JupyterLite integration - assessment

### ISSUE THREAD

**Issue by aplamada** [inseri-swiss/inseri-swiss#132]
Jupyter is very popular within the research community. 
It is desired to have a JupyterLite integration. More thoughts are needed to define the functional specification.
- similar to Python Code
- in extended view JupyterLab is available
- in order to identify the file to run, the user can select a MAIN file. Inputs and Outputs are relative to the MAIN file
- in normal mode if possible REPLlite with the MAIN file is displayed

**Comment by bigaru** [comment]
Here is the [Github repo](https://github.com/jupyterlite/jupyterlite).

since it is react based, we can take inspiration from certain aspects or parts.

**Comment by aplamada** [comment]
See https://github.com/inseri-swiss/inseri-swiss/issues/150 .
