### ISSUE TITLE
WP supports block name

### ISSUE THREAD

**Issue by bigaru** [inseri-swiss/inseri-swiss#133]
see https://wordpress.com/support/advanced-block-settings/#block-name

it is stored inside attributes:
```json
{
"metadata" : {
    "name": "my block"
  }
}
```

so in order to sync between wp blockname and inseri blockname, we simply have to store at `metadata.name`

**Comment by aplamada** [comment]
At the moment, It is unclear to me whether this is helping or confusing. It will "rename" the name that appears in the List View. Maybe the "best" compromise, if feasible, is to let users decide, like "Hide the invisible blocks" with a new option "Update Block Name in List View"

It is unclear to me whether this is a breaking change or not. So far we support WP>5.6 . In case we populate that attribute, can it be that WP will complain?

<img width="674" alt="image" src="https://github.com/inseri-swiss/inseri-swiss/assets/3380515/875aa7a6-dcaa-466e-a873-7528cc527a24">
