### ISSUE TITLE
new dropdown single choice block

### ISSUE THREAD

**Issue by aplamada** [inseri-swiss/inseri-swiss#14]
**Input**: json array from
- manual user, or
- from a Media Library, Inseri Data Source, or code block instance 

**Output**: selected item

- select one element
- able to search an element

**Comment by bigaru** [comment]
insights: 
- to retrieve theme colors
```ts
import { useSelect } from '@wordpress/data'
	const colorsPalette = useSelect((select: any) => {
		return select('core/block-editor').getSettings().colors
	}, []).map((c: any) => c.color)
```
