### ISSUE TITLE
Export block in a Synced Pattern

### ISSUE THREAD

**Issue by aplamada** [inseri-swiss/inseri-swiss#156]
If the Export block belongs to a pattern, the export does not work as desired:
- the original URL is wrong (the path corresponds to the name of the patern)
- the xml does not correspond to the page / post

**Comment by bigaru** [comment]
Maybe the synced pattern share the same attributes underneath.
In case of export block, everywhere the synced pattern is used, it will use the original postId

**Comment by aplamada** [comment]
it might be that the synced pattern itself has a postId.

**Comment by aplamada** [comment]
The plan is to update the docs. The export block is not compatible with the synced pattern.
