### ISSUE TITLE
DataFlow

### ISSUE THREAD

**Issue by aplamada** [inseri-swiss/inseri-swiss#22]
A [DAG](https://en.wikipedia.org/wiki/Directed_acyclic_graph) representation for the data flow between inseri block instances:
- **nodes**: the block instances - the displayed name (hover?) can be `<block name>-<instance name>` and the icon representation for the block could be reused
- **directed edges**: the data 

tasks
- [x]  create cytoscape block
- [ ]  create data flow
    - under document overview, new tab 'data flow'
    - left bar is splitted into two panels, one is list of connected block and other is network graph
    - one can open the network graph into fullscreen modal
    - if one clicks on list item or graph node, then the corresponding block is highlighted

![WhatsApp Image 2023-10-25 at 18 59 38](https://github.com/inseri-swiss/inseri-swiss/assets/13069024/da04df65-3d9e-4f95-b2b8-8c2e7fc53f83)

**Comment by aplamada** [comment]
plotly can be used to generate a scatter plot where each 2 dots are connected - see https://plotly.com/python/network-graphs/ with the small change `mode = 'lines+markers'`:
```
edge_trace = go.Scatter(
...
    mode='lines+markers', 
    marker=dict(
          symbol="arrow",
          size=15,
          angleref="previous",
            ))
```

**Comment by aplamada** [comment]
For DOT files see https://en.wikipedia.org/wiki/DOT_(graph_description_language)#JavaScript

**Comment by bigaru** [comment]
js libaries:

- https://github.com/visjs/vis-network
- https://github.com/cytoscape/cytoscape.js
- https://github.com/jacomyal/sigma.js  - the latest version is alpha since march

**Comment by aplamada** [comment]
See https://blog.js.cytoscape.org/2020/05/11/layouts/ for cytoscape layouts
