### ISSUE TITLE
assess visualisation options

### ISSUE THREAD

**Issue by aplamada** [inseri-swiss/inseri-swiss#41]
We should see the effort, functionality, ease to use for some visualization options that can be easily integrated:
- [ ] vega / vega-lite - https://github.com/vega/react-vega 
- [ ] plotly - https://plotly.com/javascript/react/

**Comment by bigaru** [comment]
With all three options it is possible to create extensive and very various charts. Furthermore, they enable to create various charts with single js object compared to [other js libraries](https://blog.logrocket.com/top-8-react-chart-libraries/):
- [react-vega](https://github.com/vega/react-vega) which is a react wrapper for [vega-embed](https://github.com/vega/vega-embed)
- [react-plotly.js](https://github.com/plotly/react-plotly.js) which is a react wrapper for [plotly.js](https://github.com/plotly/plotly.js)
- [echarts](https://github.com/apache/echarts)

react-vega/vega-embed:
- there is no direct way to listen for events
- indirectly with `signals` as part of vega spec, somehow, it can be achieved to fire events

echarts:
- there is no react component (just small obstacle)
- it offers nice way of event handling
- responsiveness needs to be implemented manually

react-plotly.js:
- it offers nice way of event handling
- in general it provides good default settings
- responsiveness can be achieved only with few config adjustments

And after local prototyping and I conclude react-plotly.js  is the good option
