### ISSUE TITLE
Assess user feedback / engagement

### ISSUE THREAD

**Issue by bigaru** [inseri-swiss/inseri-swiss#45]
similar to [swisstransfer](https://www.swisstransfer.com),  a place to receive and aggregate ideas/feedback
[![image](https://user-images.githubusercontent.com/13069024/208241424-8b149513-5087-4ff0-942d-a6ee1c93f5ef.png)](https://feedback.userreport.com/f12466ad-db5b-4f5c-b24c-a54b0a5117ca/#ideas/popular)

**Comment by bigaru** [comment]
many opensource projects (like mantine, chakra-ui, bun, ...) they have discord server

in this way, users can help each other
![image](https://user-images.githubusercontent.com/13069024/214646375-8176d8c3-89fa-4f32-9e7f-0ebc9b55023b.png)

**Comment by aplamada** [comment]
For MVP:
- GitHub issues / maybe discussions (no need for templates), hashtag on Stackoverflow?!
- no live chat
- one place to report can even be nice

To reassess it later.

**Comment by aplamada** [comment]
For MVP:
- GitHub issues, GitHub discussions and stackoverflow.

Regarding stackoverflow hashtag - we will suggest #inseri and we have to follow both:
- https://wordpress.stackexchange.com/
- https://stackoverflow.com/
