### ISSUE TITLE
Web API: assess DaSCH

### ISSUE THREAD

**Issue by aplamada** [inseri-swiss/inseri-swiss#49]
The aim is to assess whether public data stored in DaSCH can be easily used in inseri.

Expected something similar to #13

**Comment by rfbaumgartner** [comment]
The other entry point is the extended search with POST `https://api.dasch.swiss/v2/extendedsearch` and a body with Gravsearch. The result can be mapped to an input array for a dropdown for example. I see two particularities: The results will be paginated, and the query in the body might need some interpolation to get different data (e.g. in chained selection).

**Comment by rfbaumgartner** [comment]
Conclusion:

Single resources can be shown in JSON or any other format after a conversion with just the standard components.

The extended search can be used to collect table data or input for a dropdown. 

If pagination through a list of resources would be needed, a separate class of requests with an IRI as input would be a nice solution.

**Comment by rfbaumgartner** [comment]
For both, the resource route and the extended search, the default customizations in the API are enough. Customization of the path (resource route) or the body (extended search) is enough.

In case a project wants to use DaSCH as a backend for inseri, they will have to approach DaSCH.
