### ISSUE TITLE
Publish as an official Plugin

### ISSUE THREAD

**Issue by aplamada** [inseri-swiss/inseri-swiss#72]
The aim is to have inseri core available via the official repo https://wordpress.org/plugins/ .
See https://developer.wordpress.org/plugins/ for creating this.

- [x] clean up code
- [x] [Plugin Directory Guidelines](https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/)
- [x] [Community Guidelines](https://make.wordpress.org/handbook/community-code-of-conduct/)
- [x] [Block guidelines](https://developer.wordpress.org/plugins/wordpress-org/block-specific-plugin-guidelines/)
- [x] README.txt 
- [ ] block example - aborted, it seems that mantine styling is not working
- [x] changelog
- [x] submit to review

**Comment by bigaru** [comment]
maybe we need rename some blocks:
see https://developer.wordpress.org/plugins/wordpress-org/block-specific-plugin-guidelines/#3-plugin-and-block-names-should-reflect-the-blocks-purpose:

> The same trademark restrictions for plugin titles exist for block titles and names. This means that a block may not be named “Facerange Block” unless developed by a legal representative of Facerange

**Comment by aplamada** [comment]
- add systematically a suffix like ` - inseri`
- rename "Plotly.js" to "Plotly Chart" and add the suffix
- rename "Zenodo" to "Zenodo Repository"

**Comment by bigaru** [comment]
I submitted to WP and it was estimated up to 30 days.
